
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: WARN
    com.yourcompany: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  health:
    db:
      enabled: true
    diskspace:
      threshold: 10MB

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shoyebmd424/product-store.git
          clone-on-start: true
          default-label: main
          searchPaths: congfigserver/src/main/resources

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: config-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8087/eureka/