
spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8080
  datasource:
    url: jdbc:h2:mem:authservice
    driver-class-name:  org.h2.Driver
    username: root
    password: root

  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081
